### ISSUE TITLE
Possible issue with env file

### ISSUE THREAD

**Issue by Opegraphy** [richiedlon/RSensePy#3]
Please look into the issue with the environment file that seems to be stopping the last 6 indices from running. Please see attached screenshot for the error encountered during testing.

![image](https://github.com/richiedlon/SoftwareDevProject/assets/80511315/7f849c2f-92a3-4439-b748-3b6d2360c88f)

**Comment by Opegraphy** [comment]
![Uploading image.png…]()

**Comment by Opegraphy** [comment]
![image](https://github.com/richiedlon/SoftwareDevProject/assets/80511315/f276d483-f66d-4117-8efe-47414bbf150c)

**Comment by richiedlon** [comment]
There is no issue with the environment file. The incorrect clipping function has been used. For instance, the input is a bounding box but within the class functions tou are trying to clip using the clipshape file function. Instead need to use the clip with bounding box function. I change gli index now it works. Please check the same error for other index that are not working.
